# Generated by Django 6.0.6 on 2026-06-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidate_image_alter_candidate_id_alter_position_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
