# Generated by Django 5.2.15 on 2026-06-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='login_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
